In [ ]:
!nvidia-smi

# [1] PyTorch Fundamentals

In [ ]:
'''
* Machine laerning is turning things (data) into numbers and finding patterns in those numbers.

* Why use machine/deep learning?
- For a complex problem, can you think of all the rules? (probably not).
- If you can build a simple rule-based system that doesn't require machine learning, do that. (maybe not very simple...)

* What deep learning is good for?
- Problems with long lists of rules - when the traditional approach fails, machine learning/deep learning may help.
- Continually changing environments - deep learning can adapt('learn') to new scenarios.
- Discovering insights within large collections of data - can you imagine trying to hand-craft rules for
  what 101 different kinds of food look like?

* What deep learning is not good for?
- When you need explainability - the patterns learned by a deep learning model are typically uninterpretable by a human.
- When the traditional approach is a better option - if you can accomplish what you need with a simple rule-based system.
- When errors are unacceptable - since the outputs of deep learning model aren't always predictable.
- When you don't have much data - deep learning models usually require a fairly large amount of data to produce greate results.
  (thouogh we'll see how to get great results without huge amounts of data).

* Machine Learning vs. Deep Learning
1) Machine Learning
  - Structured data
  - algorithms: Random forest, Gradient boosted models, Naive Bayes, Nearest neighbour, Support vector mahcine, etc.

2) Deep Learning
  - Unstructured data
  - algorithms: Neural networks, Fully connected neural network, Convolutional neural network, Recurrent neural network, Transformer, etc.

=> depending how you represent your problem, many algorithms can be used for both.

* What are neural networks?
1) Inputs (text, images, speech)
2) Numerical encoding - before data gets used with a neural network, it needs to be turned into numbers.
3) Learns representation (patterns/features/weights) - choose the appropriate neural network for your problem.
4) Representation outputs
5) Outputs - a human can understand these.

* Anatomy of Neural Networks
1) Input layer : data goes in here
2) Hidden layer(s) : learns patterns in data
3) Output layer : outputs learned representation or prediction probabilities

- Each layer is usually combination of linear (straight line) and/or non-linear (not-straight line) functions.
- Note: "patterns" is an arbitrary term, you'll ofen hear "embedding", "weights", "feature representation", "feature vectors"
  all referring to similar things.

* Types of Learning
1) Supervised Learning
2) Unsupervised & Self-supervised Learning
3) Transfer Learning
4) Reinforcement Learning

* Deep Learning Use Cases
- Recommendation
- Translation : (Sequence to sequence : seq2seq)
- Speech recognition : (Sequence to sequence : seq2seq)
- Computer Vision : (Classification/regression)
- Natural Language Processing (NLP) : (Classification/regression)

* What is PyTorch?
- Most popular research deep learning framework
- Write fast deep learning code in Python (able to run on a GPU/many GPUs)
- Able to access many pre-built deep learning models (Torch Hub / torchvision.models)
- Whole stack: preprocess data, model data, deploy model in your application/cloud
- Originally designed and used in-house by Facebook/Meta (now open-source and used by companies such as Tesla, Microsoft, OpenAI)

* Why PyTorch?
- Tesla Autopilot
- OpenAI Standardize on PyTorch
- PyTorch builds the future of AI and machine learning at Facebook
- AI for AG: Production machine learning for agriculture

* What is a GPU/TPU?
- GPU: Graphics Processing Unit
- TPU: Tensor Processing Unit

* What we're going to cover
- PyTorch basics & fundamentals (dealing with tensors and tensor operations)
- Preprocessing data (getting it into tensors)
- Building and using pretrained deep learning models
- Fitting a model to the data (learning patterns)
- Making predictions with a model (using patterns)
- Evaluating model predictions
- Saving and loading models
- Using a trained model to make predictions on custom data

'''

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1][1]

tensor(10)

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                                         [3,6,9],
                                         [2,4,5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many nueral networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9295, 0.8645, 0.1034, 0.7503],
        [0.2719, 0.9544, 0.7042, 0.2985],
        [0.7221, 0.3303, 0.3732, 0.1971]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.0119, 0.0146, 0.1519, 0.8475, 0.2745, 0.2900, 0.4501, 0.8506,
          0.8883, 0.6775],
         [0.6283, 0.5618, 0.3960, 0.8992, 0.0197, 0.2499, 0.4104, 0.2216,
          0.4250, 0.7204],
         [0.1841, 0.2149, 0.0101, 0.7728, 0.6367, 0.3497, 0.8092, 0.5926,
          0.2835, 0.8387],
         [0.6914, 0.9014, 0.5764, 0.8944, 0.6820, 0.5576, 0.9106, 0.3829,
          0.0896, 0.2048],
         [0.0931, 0.3388, 0.4913, 0.1608, 0.2062, 0.3494, 0.0603, 0.0673,
          0.6844, 0.6716],
         [0.4709, 0.9001, 0.5295, 0.7728, 0.8638, 0.1987, 0.7034, 0.1635,
          0.8091, 0.3812],
         [0.3550, 0.3615, 0.9697, 0.5156, 0.5116, 0.0967, 0.7746, 0.3520,
          0.3843, 0.2744],
         [0.3835, 0.7079, 0.2833, 0.3225, 0.0257, 0.5471, 0.7528, 0.6518,
          0.7804, 0.7626],
         [0.1449, 0.3419, 0.7691, 0.0861, 0.0834, 0.8051, 0.1367, 0.0485,
          0.8341, 0.8905],
         [0.0676, 0.6122, 0.2078, 0.6320, 0.4618, 0.7933, 0.0028, 0.9155,
          0.5384,

In [ ]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([1, 10, 10])


In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R, G, B)

print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros and ones

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4181, 0.0786, 0.7077, 0.3186],
        [0.3953, 0.6078, 0.7423, 0.6170],
        [0.3852, 0.4287, 0.3991, 0.0170]])

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones * random_tensor

tensor([[0.4181, 0.0786, 0.7077, 0.3186],
        [0.3953, 0.6078, 0.7423, 0.6170],
        [0.3852, 0.4287, 0.3991, 0.0170]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
with_steps = torch.arange(start=0, end=1000, step=77)
with_steps

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0 ,6.0, 9.0],
                               dtype=None,                           # what datatype is the tensor (e.g. float32 or float16)
                               device=None,                         # "cpu" or "cuda" What device is your tensor on
                               requires_grad=False)             # Whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# change datatype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1681, 0.9040, 0.1509, 0.4556],
        [0.5984, 0.2786, 0.8170, 0.3000],
        [0.7887, 0.8483, 0.4585, 0.2497]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print()
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # some_tensor.size()
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1681, 0.9040, 0.1509, 0.4556],
        [0.5984, 0.2786, 0.8170, 0.3000],
        [0.7887, 0.8483, 0.4585, 0.2497]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tenosr and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` wll work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [ ]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.59 ms, sys: 964 µs, total: 2.56 ms
Wall time: 3.11 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 200 µs, sys: 7 µs, total: 207 µs
Wall time: 125 µs


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4153, 0.2099, 0.8311],
        [0.0262, 0.0923, 0.2282],
        [0.4596, 0.1912, 0.8286]])

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.1846, 1.5597],
        [0.8116, 1.0918]])

### One of the most common errors in deep learning: shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

print(tensor_A)
print(tensor_B)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T) # torch.mm

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
print(tensor_B)
print()
print(tensor_B.shape)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

torch.Size([3, 2])


In [ ]:
print(tensor_B.T)
print()
print(tensor_B.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]])

torch.Size([2, 3])


In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match\n")
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in tensor that has the minimum value with argmin()
# -> returns index position of target tensor where the minimum value occurs.
x.argmin()

tensor(0)

In [ ]:
# Finde th position in tensor that has the maximum value with argmax()
# -> returns index position of target tensor where the maximum value occurs.
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_vstacked = torch.vstack([x,x,x,x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_hstacked = torch.hstack([x,x,x,x])
x_hstacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() - removes all single dimension from a target tensor

print(f"Previous tensor: {x_reshaped}\n")
print(f"Previous shape: {x_reshaped.shape}\n")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}\n")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}\n")
print(f"Previous shape: {x_squeezed.shape}\n")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}\n")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}\n")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape: torch.Size([9, 1])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

sample = torch.randn(2,3,5)
sample.size()

torch.Size([2, 3, 5])

In [ ]:
torch.permute(sample, (2,0,1)).size()

torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}\n")
print(f"New shape: {x_permuted.shape}") # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0] = 728218

print(x_original[0,0,0])
print(x_permuted[0,0,0])

tensor(728218.)
tensor(728218.)


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,0,1]

tensor(2)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch tensors & Numpy

Numpy is a popular scientific python numerical computing labrary.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor

array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# warning: when converting from numpy -> pytorch,
# pytorch reflects numpy's default datatype of float64 unless specified otherwise.

In [ ]:
# Change the value of array, what will this do to `tensor`?
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again... `

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0274, 0.4408, 0.8917, 0.8339],
        [0.5290, 0.9808, 0.3690, 0.4027],
        [0.7276, 0.6556, 0.2664, 0.2597]])
tensor([[0.1948, 0.1608, 0.4448, 0.5938],
        [0.9552, 0.4617, 0.1622, 0.3158],
        [0.6080, 0.4780, 0.2666, 0.8014]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Wed Jan 24 03:38:45 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g., run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy

# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')